### ISSUE TITLE
Nivo Slider shortcode is not working

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/fara#11]
@rodica-andronache In the slider section of this theme nivo slider shortcode is not working while meta slider shortcode works properly.
See screenshots: http://prntscr.com/fgx7n2 http://prntscr.com/fgx86v

**Comment by rodica-andronache** [comment]
@dragosey If you want, you can try to investigate/fix this one when you can :)

**Comment by rodica-andronache** [comment]
@dragosey make sure you don't upload .idea/vcs.xml from PHPStorm :D
