### ISSUE TITLE
can't remove author and posted date

### ISSUE THREAD

**Issue by netking22** [Codeinwp/fara#4]
i want to remove author details from post list, listed on home page i can't find the option to remove the details from post . i want to hide all of them. i want to show only post titile and thumbnail.

**Comment by rodica-andronache** [comment]
Hi @netking22 ,

We really take the requests of our people dearly, but yours is a bit beyond the support service we normally offer for free products, as the theme does not have an option for this, so this is not a bug. 
But, just this time, let me try to help you :)
You can add a custom css for that :
`.blog span.posted-on, .blog span.post-cat {
    display: none;
}`

Regards,
Rodica
