### ISSUE TITLE
Wrong slug in TGM plugin register function

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/fara#8]
In TGM Plugin register function, the slug for WP product review plugin is misspelled as "wp-product-reviews" the correct slug is "wp-product-review", because of that the plugin activation link doesn't work in WP dashboard and gives an error, see screenshot http://prntscr.com/f9dupc

**Comment by rodica-andronache** [comment]
@poonam279 thanks :) You just forgot to make a pull request, so I made it

**Comment by poonam279** [comment]
@rodica-andronache Thank you :)
